# Generated by Django 3.2.4 on 2021-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20211028_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('100000', 100000), ('200000', 200000), ('300000', 300000), ('400000', 400000), ('500000', 500000), ('600000', 600000), ('700000', 700000), ('800000', 800000), ('900000', 900000), ('1000000', 1000000)]),
        ),
    ]
